spring:
  application:
    name: authserver
  datasource:
    url: jdbc:postgresql://localhost:5433/authserver
    username: authserver
    password: authserver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 9000

logging:
  level:
    org.springframework.security: DEBUG

admin:
  client-secret: ${ADMIN_CLIENT_SECRET}
  console-username: ${ADMIN_CONSOLE_USERNAME}
  console-password: ${ADMIN_CONSOLE_PASSWORD}
  console-client-secret: ${ADMIN_CONSOLE_CLIENT_SECRET}